# Generated by Django 6.0.1 on 2026-02-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва категорії')),
                ('link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Посилання на категорію')),
                ('status', models.CharField(choices=[('New', 'New'), ('Done', 'Done')], default='New', max_length=50, verbose_name='Статус категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='allo.ua', max_length=255, verbose_name='Сайт')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('name', models.CharField(max_length=500, verbose_name='Назва товару')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='Посилання')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул (SKU)')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна до знижки')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна зі знижкою')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% знижки')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума знижки')),
                ('additional_info', models.JSONField(blank=True, default=dict, verbose_name='Додаткова інформація')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано до БД')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='parser_app.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-discount_percent'],
            },
        ),
    ]
