# Generated by Django 6.0.1 on 2026-02-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Error', 'Error')], default='Pending', max_length=50, verbose_name='Статус товару'),
        ),
    ]
