# Generated by Django 6.0.1 on 2026-02-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availabily',
            field=models.CharField(choices=[('InStock', 'In Stock'), ('LimitedAvailability', 'Limited Availability')], default='InStock', max_length=50, verbose_name='Наявність'),
        ),
    ]
